/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <android/log.h>
#include <interf_enc.h>
#include <string.h>

#ifndef _Included_com_hikvh_media_amr_AmrEncoder
#define _Included_com_hikvh_media_amr_AmrEncoder

struct encoder_state *state;

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL
Java_io_kvh_media_amr_AmrEncoder_init(JNIEnv *env, jclass type, jint dtx) {
    state = (encoder_state *) Encoder_Interface_init(dtx);
}

JNIEXPORT void JNICALL
Java_io_kvh_media_amr_AmrEncoder_reset(JNIEnv *env, jclass type) {
    Encoder_Interface_reset(state);
}

JNIEXPORT void JNICALL
Java_io_kvh_media_amr_AmrEncoder_exit(JNIEnv *env, jclass type) {
    Encoder_Interface_exit(state);
}

JNIEXPORT jint JNICALL
Java_io_kvh_media_amr_AmrEncoder_encode
        (JNIEnv *env, jclass, jint mode, jshortArray in, jbyteArray out) {

    jsize inLen = env->GetArrayLength(in);
    jshort inBuf[inLen];
    env->GetShortArrayRegion(in, 0, inLen, inBuf);

    jsize outLen = env->GetArrayLength(out);
    jbyte outBuf[outLen];
    int encodeLength;

    encodeLength = Encoder_Interface_Encode(state, (Mode) mode, (const short *) inBuf,
                                            (unsigned char *) outBuf);

    env->SetByteArrayRegion(out, 0, outLen, outBuf);
    return encodeLength;
}

#ifdef __cplusplus
}
#endif
#endif
